import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CalendarDays, Download, Plus, Printer, Upload, Users, X } from "lucide-react";
import { api } from "./api";

type Leader={id:string;name:string}; type Group={id:string;name:string;leaderIds:string[]};
type Task={id:string;title:string;leaderIds:string[]};
type PlanItem={id:string;title:string;kind:"activity"|"meal"|"general";date:string;start:string;end:string;location:string;groupIds:string[];leaderIds:string[];tasks:Task[];notes:string;siteInstructors:boolean};
type Plan={leaders:Leader[];groups:Group[];items:PlanItem[]};
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const minutes=(time:string)=>{const [h,m]=time.split(":").map(Number);return h*60+m};
const dates=(start:string,end:string)=>{const out:string[]=[];const d=new Date(start+"T12:00:00"),last=new Date(end+"T12:00:00");while(d<=last){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out};
const labelDate=(date:string)=>new Date(date+"T12:00:00").toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short"});
const blank=(date:string):PlanItem=>({id:"",title:"",kind:"activity",date,start:"09:00",end:"10:00",location:"",groupIds:[],leaderIds:[],tasks:[],notes:"",siteInstructors:false});

export function PlannerTab({eventId,eventName,start,end}:{eventId:string;eventName:string;start:string;end:string}){
  const first=start.slice(0,10),last=end.slice(0,10),storageKey=`campcomms-planner-${eventId}`;
  const [plan,setPlan]=useState<Plan>({leaders:[],groups:[],items:[]}); const [loaded,setLoaded]=useState(false),[saveState,setSaveState]=useState<"loading"|"saved"|"saving"|"offline"|"error">("loading");
  const [day,setDay]=useState(first),[edit,setEdit]=useState<PlanItem|null>(null),[view,setView]=useState<"programme"|"people"|"print">("programme"),[drag,setDrag]=useState("");
  const upload=useRef<HTMLInputElement>(null); const campDays=useMemo(()=>dates(first,last),[first,last]);
  useEffect(()=>{let active=true;void api<{plan:Plan|null}>(`/api/events/${eventId}/planner`).then(async result=>{if(!active)return;const local=localStorage.getItem(storageKey);if(result.plan){setPlan({...result.plan,items:result.plan.items.map(item=>({...item,tasks:item.tasks??[],siteInstructors:item.siteInstructors??false}))});setSaveState("saved")}else if(local){const cached=JSON.parse(local) as Plan;const upgraded={...cached,items:cached.items.map(item=>({...item,tasks:item.tasks??[],siteInstructors:item.siteInstructors??false}))};setPlan(upgraded);await api(`/api/events/${eventId}/planner`,{method:"PATCH",body:JSON.stringify({plan:upgraded})});setSaveState("saved")}else setSaveState("saved");setLoaded(true)}).catch(()=>{if(!active)return;try{const cached=localStorage.getItem(storageKey);if(cached){const parsed=JSON.parse(cached) as Plan;setPlan({...parsed,items:parsed.items.map(item=>({...item,tasks:item.tasks??[],siteInstructors:item.siteInstructors??false}))})}}catch{}setLoaded(true);setSaveState("offline")});return()=>{active=false}},[eventId,storageKey]);
  useEffect(()=>{if(!loaded)return;localStorage.setItem(storageKey,JSON.stringify(plan));setSaveState(navigator.onLine?"saving":"offline");const timer=window.setTimeout(()=>{void api(`/api/events/${eventId}/planner`,{method:"PATCH",body:JSON.stringify({plan})}).then(()=>setSaveState("saved")).catch(()=>setSaveState(navigator.onLine?"error":"offline"))},700);return()=>window.clearTimeout(timer)},[plan,loaded,storageKey,eventId]);
  const warnings=useMemo(()=>{const found:{ids:string[];text:string}[]=[];for(let i=0;i<plan.items.length;i++)for(let j=i+1;j<plan.items.length;j++){const a=plan.items[i],b=plan.items[j];if(a.date!==b.date||minutes(a.start)>=minutes(b.end)||minutes(b.start)>=minutes(a.end))continue;if(a.leaderIds.some(x=>b.leaderIds.includes(x)))found.push({ids:[a.id,b.id],text:`Leader clash: ${a.title} and ${b.title}`});if(a.groupIds.some(x=>b.groupIds.includes(x)))found.push({ids:[a.id,b.id],text:`Group clash: ${a.title} and ${b.title}`})}return found},[plan.items]);
  const save=(item:PlanItem)=>{if(!item.title.trim())return;if(minutes(item.end)<=minutes(item.start))return alert("The end time must be after the start time.");if(!campDays.includes(item.date))return alert("Choose a date during camp.");const value={...item,id:item.id||id()};setPlan(p=>({...p,items:p.items.some(x=>x.id===value.id)?p.items.map(x=>x.id===value.id?value:x):[...p.items,value]}));setEdit(null)};
  const backup=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(plan,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`${eventName.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-programme.json`;a.click();URL.revokeObjectURL(url)};
  const restore=async(file?:File)=>{if(!file)return;try{const next=JSON.parse(await file.text());if(!Array.isArray(next.items)||!Array.isArray(next.groups)||!Array.isArray(next.leaders))throw new Error();setPlan(next)}catch{alert("This is not a valid CampComms planner backup.")}};
  return <div className="planner-page">
    <section className="planner-head"><div><p className="eyebrow">Leader tool · {saveState==="saved"?"saved to CampComms":saveState==="saving"?"saving…":saveState==="loading"?"loading…":saveState==="offline"?"offline copy saved":"save needs retry"}</p><h2>Camp programme planner</h2><p>Build the programme, check assignments and print copies for everyone.</p></div><div className="planner-actions"><button className="secondary-button" onClick={backup}><Download size={16}/>Backup</button><button className="secondary-button" onClick={()=>upload.current?.click()}><Upload size={16}/>Restore</button><input hidden ref={upload} type="file" accept=".json" onChange={e=>void restore(e.target.files?.[0])}/><button className="primary-button" onClick={()=>setEdit(blank(day))}><Plus size={17}/>Add item</button></div></section>
    <nav className="planner-view-tabs"><button className={view==="programme"?"active":""} onClick={()=>setView("programme")}><CalendarDays size={17}/>Programme</button><button className={view==="people"?"active":""} onClick={()=>setView("people")}><Users size={17}/>People & groups</button><button className={view==="print"?"active":""} onClick={()=>setView("print")}><Printer size={17}/>Print</button></nav>
    {view==="programme"&&<><div className="planner-days">{campDays.map((date,index)=><button key={date} className={day===date?"active":""} onClick={()=>setDay(date)} onDragOver={e=>e.preventDefault()} onDrop={()=>{setPlan(p=>({...p,items:p.items.map(x=>x.id===drag?{...x,date}:x)}));setDay(date)}}><small>Day {index+1}</small><strong>{labelDate(date)}</strong><span>{plan.items.filter(x=>x.date===date).length} items</span></button>)}</div><div className="planner-columns"><section className="planner-card"><header><h3>{labelDate(day)}</h3><button className="icon-button" onClick={()=>setEdit(blank(day))}><Plus size={18}/></button></header><div className="planner-list">{plan.items.filter(x=>x.date===day).sort((a,b)=>a.start.localeCompare(b.start)).map(item=><button draggable onDragStart={()=>setDrag(item.id)} className={`planner-item ${item.kind}`} key={item.id} onClick={()=>setEdit(item)}><time><strong>{item.start}</strong><span>{item.end}</span></time><span className="planner-item-main"><strong>⠿ {item.title}{item.siteInstructors?" *":""}</strong><small>{item.location||"No location"}</small><span>{item.groupIds.map(g=>plan.groups.find(x=>x.id===g)?.name).filter(Boolean).join(" · ")||"No groups assigned"}</span></span>{warnings.some(w=>w.ids.includes(item.id))&&<i>!</i>}</button>)}{!plan.items.some(x=>x.date===day)&&<button className="planner-empty" onClick={()=>setEdit(blank(day))}><Plus/><strong>Add the first item</strong><span>Activities, meals and general camp events all go here.</span></button>}</div></section><aside className="planner-card planner-health"><header><h3>Plan health</h3><b>{warnings.length||"✓"}</b></header>{warnings.length?warnings.map((warning,index)=><p key={index}><AlertTriangle size={16}/>{warning.text}</p>):<p className="clear">✓ No leader or group clashes</p>}<div className="planner-hint">Drag an item onto a different day. Edit it to change its time in 15-minute steps.</div></aside></div></>}
    {view==="people"&&<People plan={plan} setPlan={setPlan}/>} {view==="print"&&<PrintProgramme plan={plan} days={campDays} eventName={eventName}/>} {edit&&<Editor item={edit} plan={plan} first={first} last={last} close={()=>setEdit(null)} save={save}/>} </div>
}

function People({plan,setPlan}:{plan:Plan;setPlan:(p:Plan)=>void}){return <div className="planner-people"><section className="planner-card"><header><h3>Leaders</h3><button className="secondary-button" onClick={()=>setPlan({...plan,leaders:[...plan.leaders,{id:id(),name:"New leader"}]})}><Plus size={15}/>Add</button></header>{plan.leaders.map(person=><div className="planner-person" key={person.id}><input aria-label="Leader name" value={person.name} onChange={e=>setPlan({...plan,leaders:plan.leaders.map(x=>x.id===person.id?{...x,name:e.target.value}:x)})}/><button className="icon-button" onClick={()=>setPlan({...plan,leaders:plan.leaders.filter(x=>x.id!==person.id)})}><X size={16}/></button></div>)}</section><section className="planner-card"><header><h3>Scout groups</h3><button className="secondary-button" onClick={()=>setPlan({...plan,groups:[...plan.groups,{id:id(),name:"New group",leaderIds:[]}]})}><Plus size={15}/>Add</button></header>{plan.groups.map(group=><div className="planner-group" key={group.id}><input aria-label="Group name" value={group.name} onChange={e=>setPlan({...plan,groups:plan.groups.map(x=>x.id===group.id?{...x,name:e.target.value}:x)})}/><small>Suggested leaders</small><div className="planner-checks">{plan.leaders.map(person=><label key={person.id}><input type="checkbox" checked={group.leaderIds.includes(person.id)} onChange={()=>setPlan({...plan,groups:plan.groups.map(x=>x.id===group.id?{...x,leaderIds:x.leaderIds.includes(person.id)?x.leaderIds.filter(v=>v!==person.id):[...x.leaderIds,person.id]}:x)})}/>{person.name}</label>)}</div></div>)}</section></div>}

function Editor({item,plan,first,last,close,save}:{item:PlanItem;plan:Plan;first:string;last:string;close:()=>void;save:(x:PlanItem)=>void}){
  const [draft,setDraft]=useState({...item,groupIds:[...item.groupIds],leaderIds:[...item.leaderIds],tasks:(item.tasks??[]).map(task=>({...task,leaderIds:[...task.leaderIds]}))});
  const updateTask=(taskId:string,patch:Partial<Task>)=>setDraft(value=>({...value,tasks:value.tasks.map(task=>task.id===taskId?{...task,...patch}:task)}));
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal planner-modal"><header><h2>{item.id?"Edit programme item":"Add programme item"}</h2><button className="icon-button" onClick={close}><X/></button></header><form onSubmit={e=>{e.preventDefault();save(draft)}}>
    <div className="planner-kinds">{(["activity","meal","general"] as const).map(kind=><button type="button" className={draft.kind===kind?"active":""} onClick={()=>setDraft({...draft,kind})} key={kind}>{kind[0].toUpperCase()+kind.slice(1)}</button>)}</div>
    <label>Title<input autoFocus required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
    {draft.kind==="activity"&&<label className="planner-site-instructors"><input type="checkbox" checked={draft.siteInstructors} onChange={e=>setDraft({...draft,siteInstructors:e.target.checked})}/> Site instructors</label>}
    <div className="field-row"><label>Date<input type="date" min={first} max={last} value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Start<input type="time" step="900" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>End<input type="time" step="900" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label></div>
    <label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label>
    <fieldset><legend>Groups <small>— their usual leaders are suggested</small></legend><div className="planner-checks">{plan.groups.map(group=><label key={group.id}><input type="checkbox" checked={draft.groupIds.includes(group.id)} onChange={()=>{const adding=!draft.groupIds.includes(group.id);setDraft({...draft,groupIds:adding?[...draft.groupIds,group.id]:draft.groupIds.filter(x=>x!==group.id),leaderIds:adding?[...new Set([...draft.leaderIds,...group.leaderIds])]:draft.leaderIds})}}/>{group.name}</label>)}</div></fieldset>
    <fieldset><legend>Activity leaders</legend><div className="planner-checks">{plan.leaders.map(person=><label key={person.id}><input type="checkbox" checked={draft.leaderIds.includes(person.id)} onChange={()=>setDraft({...draft,leaderIds:draft.leaderIds.includes(person.id)?draft.leaderIds.filter(x=>x!==person.id):[...draft.leaderIds,person.id]})}/>{person.name}</label>)}</div></fieldset>
    <fieldset className="planner-tasks"><legend>Leader tasks</legend><p>Break the item into jobs such as medicines, bags, register or car park.</p>{draft.tasks.map(task=><div className="planner-task" key={task.id}><input aria-label="Task" placeholder="Task, e.g. Collect medicines" value={task.title} onChange={e=>updateTask(task.id,{title:e.target.value})}/><button type="button" className="icon-button" aria-label="Remove task" onClick={()=>setDraft({...draft,tasks:draft.tasks.filter(x=>x.id!==task.id)})}><X size={15}/></button><div className="planner-checks">{plan.leaders.map(person=><label key={person.id}><input type="checkbox" checked={task.leaderIds.includes(person.id)} onChange={()=>updateTask(task.id,{leaderIds:task.leaderIds.includes(person.id)?task.leaderIds.filter(x=>x!==person.id):[...task.leaderIds,person.id]})}/>{person.name}</label>)}</div></div>)}<button type="button" className="secondary-button" onClick={()=>setDraft({...draft,tasks:[...draft.tasks,{id:id(),title:"",leaderIds:[]}]})}><Plus size={15}/>Add task</button></fieldset>
    <label>Organiser notes<textarea rows={3} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><footer><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button">Save item</button></footer>
  </form></section></div>
}

function PrintProgramme({plan,days,eventName}:{plan:Plan;days:string[];eventName:string}){
  const [mode,setMode]=useState<"scouts"|"organiser"|"leader">("scouts"),[leader,setLeader]=useState(plan.leaders[0]?.id||"");
  const relevant=plan.items.filter(item=>mode!=="leader"||item.leaderIds.includes(leader)||(item.tasks??[]).some(task=>task.leaderIds.includes(leader))||item.kind!=="activity");
  const firstSlot=Math.max(0,Math.floor(Math.min(8*60,...relevant.map(item=>minutes(item.start)))/15)*15);
  const lastSlot=Math.min(24*60,Math.ceil(Math.max(21*60,...relevant.map(item=>minutes(item.end)))/15)*15);
  const slots=Array.from({length:Math.max(0,(lastSlot-firstSlot)/15)},(_,index)=>firstSlot+index*15);
  const slotLabel=(slot:number)=>`${String(Math.floor(slot/60)).padStart(2,"0")}:${String(slot%60).padStart(2,"0")}`;
  return <><section className="planner-card planner-print-controls"><div><h3>Print programme</h3><p>A4 landscape timetable with times down the left and camp days across the top.</p></div><div className="planner-kinds"><button className={mode==="scouts"?"active":""} onClick={()=>setMode("scouts")}>Scouts</button><button className={mode==="organiser"?"active":""} onClick={()=>setMode("organiser")}>Organiser</button><button className={mode==="leader"?"active":""} onClick={()=>setMode("leader")}>Leader</button></div>{mode==="leader"&&<select value={leader} onChange={e=>setLeader(e.target.value)}>{plan.leaders.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select>}<button className="primary-button" onClick={()=>window.print()}><Printer size={17}/>Print</button></section>
    <section className="planner-paper"><header><h1>⚜ {eventName}</h1><h2>{mode==="scouts"?"Scout programme":mode==="organiser"?"Organiser master copy":`${plan.leaders.find(x=>x.id===leader)?.name||"Leader"} · personal programme`}</h2><span className="planner-print-legend">* Site instructors</span></header><div className="planner-timetable" style={{gridTemplateColumns:`52px repeat(${days.length}, minmax(0, 1fr))`}}><div className="planner-corner">Time</div>{days.map(date=><div className="planner-day-head" key={date}>{labelDate(date)}</div>)}{slots.map(slot=><div className="planner-time-row" key={slot} style={{gridColumn:"1 / -1",gridTemplateColumns:`52px repeat(${days.length}, minmax(0, 1fr))`}}><time>{slotLabel(slot)}</time>{days.map(date=><div className="planner-time-cell" key={date}>{relevant.filter(item=>item.date===date&&minutes(item.start)===slot).sort((a,b)=>a.start.localeCompare(b.start)).map(item=><article className={item.kind} key={item.id}><b>{item.start} {item.title}{item.siteInstructors?" *":""}</b>{item.end&&<span>to {item.end}</span>}{mode!=="scouts"&&<><span>{item.location}</span><span>{item.groupIds.map(groupId=>plan.groups.find(group=>group.id===groupId)?.name).filter(Boolean).join(", ")}</span>{item.leaderIds.length>0&&<span>Lead: {item.leaderIds.map(personId=>plan.leaders.find(person=>person.id===personId)?.name).filter(Boolean).join(", ")}</span>}{(item.tasks??[]).filter(task=>mode!=="leader"||task.leaderIds.includes(leader)).map(task=><em key={task.id}>{task.title}: {task.leaderIds.map(personId=>plan.leaders.find(person=>person.id===personId)?.name).filter(Boolean).join(", ")||"Unassigned"}</em>)}</>}</article>)}</div>)}</div>)}</div></section>
  </>
}
